CREATE SCHEMA jungle;

CREATE TABLE jungle.foods
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR (50),
    PRIMARY KEY (id)
);

CREATE TABLE jungle.animal_family
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR (50),
    PRIMARY KEY (id)
);

CREATE TABLE jungle.animals
(
    id INT GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR (50),
    legs INT,
    id_food INT,
    id_family INT,
    FOREIGN KEY (id_family) REFERENCES animal_family (id),
    FOREIGN KEY (id_food) REFERENCES foods (id),
    PRIMARY KEY (id)
);

CREATE TABLE jungle.study_excluded
(
    id_animal_excluded INT,
    PRIMARY KEY (id_animal_excluded)
);
